txn_weights:
  HIGH_VALUE_P2P:
    graph_agent: 0.40
    behaviour_agent: 0.30
    rf_agent: 0.20
    anomaly_agent: 0.10

  POS_RETAIL:
    rf_agent: 0.40
    anomaly_agent: 0.30
    graph_agent: 0.20
    behaviour_agent: 0.10

  REMITTANCE:
    graph_agent: 0.45
    geo_agent: 0.30
    behaviour_agent: 0.15
    rf_agent: 0.10

  QR_CODE:
    behaviour_agent: 0.40
    rf_agent: 0.30
    anomaly_agent: 0.20
    graph_agent: 0.10